config/routes.rb
Rails.application.routes.draw do
    
    root 'news_paper#index', as: 'news_paper_index'

	resources :news_items do
	    resources :comments
	end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  #validates :news_item, :body, :author, :presence => true
  validates_presence_of :news_item, :body, :author, :message => "no puede quedar en blanco."
  belongs_to :news_item
end

app/models/new_item.rb
class NewItem < ApplicationRecord
  has_many :comments
  validates :lead, length: {maximum: 250}, allow_blank: true

  def count_comments
    Comment.where(:new_item_id => self.id).count
  end

end

app/models/news_item.rb
class NewsItem < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :lead, length: {maximum: 250}, allow_blank: true
  default_scope { order(created_at: :desc) }
  attr_readonly :created_at
  #after_initialize :cropped_body

  def self.formatted_list
    NewsItem.all.each do |item|
      item.cropped_body
    end
  end

  def cropped_body 
    left = '...'
    nb_words_max = 1000 #+ left.length #what the user prefers
    if self.body and self.body.length > nb_words_max
      self.body = self.body.truncate(nb_words_max,
      								 separator: ' ',
      								 omission: left)
    else
      self.body
  
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index

    if params[:news_item_id]
      @news_item = NewsItem.find(id = params[:news_item_id])
      @comments = Comment.where(news_item_id: @news_item.id).entries
      @comment = @news_item.comments.build #Comment.new

    else
      @comments = Comment.all
    end

  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @news_item = NewsItem.find params[:news_item_id]
    @comment = @news_item.comments.build
    @comments = Comment.where(news_item_id: @news_item.id).entries
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @fields = {"body": "Comentario", "author": "Autor"} 

    @news_item = NewsItem.find params[:news_item_id]
    @comments = Comment.where(news_item_id: @news_item.id).entries
    @comment = @news_item.comments.build(comment_params) #Comment.new
    #@comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to new_news_item_comment_path(_index: params[:_index] , _admin: params[:_admin]),
                   notice: 'Comentario creado con éxito.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :body, :news_item_id)
    end
end

app/controllers/news_items_controller.rb
class NewsItemsController < ApplicationController
  before_action :set_news_item, only: [:show, :edit, :update, :destroy]

  # GET /news_items
  # GET /news_items.json
  def index
    @news_items = NewsItem.formatted_list
  end

  # GET /news_items/1
  # GET /news_items/1.json
  def show
      @comments = Comment.where(news_item_id: @news_item.id).entries
      @comment = @news_item.comments.build #Comment.new
  end

  # GET /news_items/new
  def new
    @news_item = NewsItem.new
    @maximum_length = NewsItem.validators_on( :lead ).first.options[:maximum]
    @current_length = 0
  end

  # GET /news_items/1/edit
  def edit
    @maximum_length = NewsItem.validators_on( :lead ).first.options[:maximum]
    @current_length = @news_item.lead.size
  end

  # POST /news_items
  # POST /news_items.json
  def create
    @news_item = NewsItem.new(news_item_params)

    respond_to do |format|
      if @news_item.save
        format.html { redirect_to new_news_item_comment_path(news_item_id:@news_item.id,
                    _index: true, _admin: true), notice: 'Noticia creada exitosamente.' }
        format.js
        format.json { render :show, status: :created, location: @news_item }
      else
        format.html { render :new }
        format.json { render json: @news_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news_items/1
  # PATCH/PUT /news_items/1.json
  def update
    respond_to do |format|
      if @news_item.update(news_item_params)
        format.html { redirect_to new_news_item_comment_path(news_item_id:@news_item.id,
                    _index: true, _admin: true), notice: 'Noticia editada exitosamente.' }
        format.json { render :show, status: :ok, location: @news_item }
      else
        format.html { render :edit }
        format.json { render json: @news_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_items/1
  # DELETE /news_items/1.json
  def destroy
    @title = @news_item.title
    @news_item.destroy
    respond_to do |format|
      format.html { redirect_to news_items_url, notice: 'Noticia "'+ @title +\
                            '" ha sido eliminada exitosamente junto a sus comentarios.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news_item
      @news_item = NewsItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_item_params
      params.require(:news_item).permit(:title, :lead, :body)
    end
end

app/controllers/news_paper_controller.rb
class NewsPaperController < ApplicationController
  def index

  	@news_items = NewsItem.limit(10).formatted_list

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/news_items_helper.rb
module NewsItemsHelper
end

app/helpers/news_paper_helper.rb
module NewsPaperHelper
end

app/views/comments/_form.html.erb
<%= render "layouts/header" %>

<%= render "layouts/navbar",  title: @news_item.title, 
index: params[:_index]=='true', admin: params[:_admin]=='true' %>


<div class="container">

  <!-- Marketing Icons Section -->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">
        <%= @news_item.title %>
      </h1>
      <p style="text-align: right;"><%= @news_item.created_at.strftime("%Y-%m-%d %H:%M:%S")  %></p>
         <p id="notice"><%= notice %></p>

    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-10">


      <div class="control-group form-group">
        <div class="controls">
          <%= @news_item.lead %>
        </div>
      </div>

      <div class='row'>
        <hr>
      </div>

      <%= form_for(@news_item) do |f| %>
      <div class="control-group form-group">
        <div class="controls">
          <%= f.text_area :body, class: 'form-control',
           cols: '100', :readonly=>true%>
        </div>
      </div>
      <% end %>





      <hr>
      <!-- Comments Form -->
      <div class="well">
        <h4><i class="fa fa-comments-o" aria-hidden="true"></i>
         Comentar:</h4>

         <%= form_for @comment , :url => news_item_comments_path(@news_item.id, @comment, 
          :_index => params[:_index]=='true', :_admin => params[:_admin]=='true'

          ) do |f| %>
          <% if comment.errors.any? %>
          <div id="error_explanation">

            <% if comment.errors.count > 1 %>
            <h2><%= comment.errors.count %> errores prohiben crear este comentario:</h2>
            <% elsif comment.errors.count == 1 %>
            <h2><%= comment.errors.count %> error prohibe crear este comentario:</h2>
            <% end %>

            <ul>
              <% comment.errors.each do |attr, message| %>
              <li>'<%= @fields[attr]%>' <%= message %></li>
              <% end %>
            </ul>
          </div>
          <% end %>

          <div class="field">
            <%= f.label :autor %>
            <br>
            <%= f.text_field :author %>
          </div>

          <div class="field">
            <%= f.label :comentario %>
            <%= f.text_area :body , class: 'form-control', rows: '5', cols: '150'%>
          </div>

          <div class="actions">
            <p style="text-align: right;">
              <%= f.submit :Enviar, class: "btn btn-primary"%>
              <p>
              </div>

              <% end %>
            </form>
          </div>




          <!-- Posted Comments -->


          <% @comments.each do |comment| %>
          <!-- Comment -->
          <div class="media">
            <a class="pull-left" href="">
              <img class="media-object" src="http://1plusx.com/app/mu-plugins/all-in-one-seo-pack-pro/images/default-user-image.png"  height="64" width="64" alt="">
            </a>
            <div class="media-body">
              <h4 class="media-heading"><%= comment.author %>:
                <small><%= comment.created_at.strftime("%Y-%m-%d %H:%M:%S") %></small>
              </h4>
              <%= comment.body %>
            </div>
          </div>
          <% end %>

        </div>
      </div>
      
      <!-- Footer -->
      <%= render "layouts/footer" %>
    </div>


    <br>
    <br>
    <br>
    <br>

  <script type="text/javascript">
    

    $(function() {
        $('textarea').each(function() {
            $(this).height($(this).prop('scrollHeight'));
        });
    });

  </script>

app/views/comments/edit.html.erb
<h1>Editar comentario</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Volver', news_item_comments_path(params[:news_item_id]) %>

app/views/comments/index.html.erb
<%= render "layouts/header" %>

<p id="notice"><%= notice %></p>

<%= render 'form', news_item_id: params[:news_item_id], comment: @comment %>

app/views/comments/new.html.erb
<%= render "layouts/header" %>

<%= render 'form', news_item_id: params[:news_item_id], comment: @comment %>

<!--%= link_to 'Volver', news_item_comments_path(params[:news_item_id], @comment) %-->

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Autor:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Noticia:</strong>
  <%= @comment.news_item.title %>
</p>

<%= link_to 'Editar', edit_news_item_comment_path(@comment.news_item.id, @comment) %>
<%= link_to 'Volver', news_item_comments_path(@comment.news_item.id, @comment) %>

app/views/layouts/_footer.html.erb
        <hr>

        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Belén Carolina Saldías Fuentes - 2017-1 - IIC3103</p>
                </div>
            </div>
        </footer>

app/views/layouts/_header.html.erb
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="tarea 01 - taller integración - 2017-1">
    <meta name="author" content="bcsaldias">

    <title>bcsaldias</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/modern-business.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

app/views/layouts/_navbar.html.erb
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href=""><%= title %></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">

                <% if admin %>
                    <li>
                        <%= link_to  'Administración', news_items_path %>
                    </li>
                <% end %>
                <% if index %>
                    <li>
                        <%= link_to  'Inicio', news_paper_index_path %>
                    </li>
                <% end %>                

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>                   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>T01</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/new_items/_form.html.erb
<%= form_for(new_item) do |f| %>
  <% if new_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(new_item.errors.count, "error") %> prohibited this new_item from being saved:</h2>

      <ul>
      <% new_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :título %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :bajada %>
      Caracteres disponibles: 
      <span id="counter" data-maximum-length="<%= @maximum_length %>">
        <%= @maximum_length - @current_length %>  
      </span>
    <br>
    <%= f.text_area :lead, maxlength: @maximum_length, id: 'lead'%>
  </div>




  <div class="field">
    <%= f.label :cuerpo %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit :Guardar%>
  </div>
<% end %>


<script>
    $(document).ready(function() {
      var review_text = $("#lead");
      var counter     = $("#counter");
      var max_length  = counter.data("maximum-length");

      review_text.keyup(function() {
          counter.text(max_length - $(this).val().length);
      });

    });
</script>

app/views/news_items/_form.html.erb
<!DOCTYPE html>
<html lang="en">

<%= render "layouts/header" %>


<body>

    <!-- Navigation -->

    <!-- Page Content -->
    <div class="container">

        <!-- Marketing Icons Section -->
        <div class="row">
            <div class="col-md-8">
                <%= form_for(news_item) do |f| %>
                  <% if news_item.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(news_item.errors.count, "error") %> prohibited this news_item from being saved:</h2>

                      <ul>
                      <% news_item.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                      </ul>
                    </div>
                  <% end %>

                  <div class="control-group form-group">
                      <div class="controls">
                          <%= f.label :título %>
                          <%= f.text_field :title, class: 'form-control' %>
                      </div>
                  </div>

                  <div class="control-group form-group">
                      <div class="controls">

                          <%= f.label :bajada %>
                            <p style="text-align: right;">caracteres disponibles:
                              <span id="counter" data-maximum-length="<%= @maximum_length %>">
                                <%= @maximum_length - @current_length %>  
                              </span>
                            </p>
                          <%= f.text_area :lead, maxlength: @maximum_length, 
                                          id: 'lead', class: 'form-control',
                                          rows: '5', cols: '100'%>
                      </div>
                  </div>

                  <div class="control-group form-group">
                      <div class="controls">
                          <%= f.label :cuerpo %>
                          <%= f.text_area :body, id: 'body', class: 'form-control',
                                          rows: '15', cols: '100'%>
                      </div>
                  </div>

                  <div class="actions">
                    <p style="text-align: right;">
                    <%= f.submit :Guardar, class: "btn btn-primary"%>
                    <p>
                  </div>
                <% end %>
            </div>


        </div>

        <%= render "layouts/footer" %>


</body>

<script type="text/javascript">
  var review_text = $("#lead");
  var counter     = $("#counter");
  var max_length  = counter.data("maximum-length");

  review_text.keyup(function() {
      counter.text(max_length - $(this).val().length);
  });
</script>>

</html>

app/views/news_items/edit.html.erb
    <!-- Navigation -->
    <%= render "layouts/navbar",  title: 'Revisión de noticia', 
                                    admin: true,
                                    index: true%>

<div class="container">

    <!-- Marketing Icons Section -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Editar noticia
            </h1>
        </div>
    </div>
</div>

<%= render 'form', news_item: @news_item %>

app/views/news_items/index.html.erb
<!DOCTYPE html>
<html lang="en">

<%= render "layouts/header" %>


<body>

    <!-- Navigation -->
    <%= render "layouts/navbar",  title: 'Noticias publicadas', 
    admin: false,
    index: true%>


    <!-- Page Content -->
    <div class="container">

        <!-- Marketing Icons Section -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    Noticias publicadas
                </h1>
            </div>
            <p id="notice"><%= notice %></p>


            <div style="text-align: right;">
                <a role="button" href="<%= new_news_item_path %>" class="btn btn-warning">Crear noticia</a>
            </div>
            

            <table  class="table table-hover" cellspacing="0" width="100%">
                <thead>
                    <tr>
                      <th>#</th>
                      <th>Título</th>
                      <th>Bajada</th>
                      <th>Cuerpo</th>
                      <th>Creado</th>
                      <th></th>
                  </tr>
              </thead>

              <tbody id="news-table">
                  <% @news_items.each_with_index do |news_item, _index| %>
                  <tr>
                      <td><%= _index %></td>
                      <td><%= news_item.title %></td>
                      <td><%= news_item.lead %></td>
                      <td><%= news_item.body %></td>
                      <td><%= news_item.created_at.strftime("%Y-%m-%d %H:%M:%S")  %></td>
                      <td><%= link_to  news_item.comments.count, new_news_item_comment_path(news_item.id, _index: true, _admin: true)%> <i class="fa fa-comments-o "></i></td>


                      <td><%= link_to  'Mostrar', new_news_item_comment_path(news_item.id, _index: true, _admin: true) %> <i class="fa fa-plus-square-o" aria-hidden="true"></i>


                      <td><%= link_to 'Editar', edit_news_item_path(news_item) %> <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                      </td>
                      <td><%= link_to 'Eliminar', news_item, method: :delete, 
                        data: { confirm: '¿Estás seguro que deseas eliminar esta noticia?' } %> <i class="fa fa-trash-o" aria-hidden="true"></i>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>

        <div class="col-md-12 text-center">
         <ul class="pagination pagination-lg pager" id="myPager"></ul>
     </div>

     <!-- Footer -->
     <%= render "layouts/footer" %>


 </div>
 <!-- /.container -->

 <!-- jQuery -->
 <script src="js/jquery.js"></script>
 <!-- Bootstrap Core JavaScript -->
 <script src="js/bootstrap.min.js"></script>
 
 <script type="text/javascript">
    $('#news-table').pageMe({pagerSelector:'#myPager',showPrevNext:true,hidePageNumbers:false,perPage:20});
</script>
</body>

</html>

app/views/news_items/new.html.erb
    <!-- Navigation -->
    <%= render "layouts/navbar",  title: 'Publicar noticia', 
                                    admin: true,
                                    index: true%>
<div class="container">
    <!-- Marketing Icons Section -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Nueva noticia
            </h1>
        </div>
    </div>
</div>

<%= render 'form', news_item: @news_item %>

<!--%= link_to 'Volver', news_items_path %-->

app/views/news_items/show.html.erb
<%= render 'comments/form', news_item_id: @news_item.id, comment: @comment %>

app/views/news_paper/index.html.erb
<!DOCTYPE html>
<html lang="en">

<%= render "layouts/header" %>

<body>


    <%= render "layouts/navbar",  title: '¡Últimas noticias!',
    admin: true,
    index: false%>



    <!-- Header Carousel -->
    <header id="myCarousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <% @news_items.each_with_index do |news_item, _index| %>
            <li data-target="#myCarousel" data-slide-to="<%= _index %>" ></li>
            <% end %>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Titulares');"></div>
                <div class="carousel-caption">
                </div>
            </div>
            <% @news_items.each do |news_item| %>
            <div class="item">
                <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=<%= news_item.title %>');"></div>
                <div class="carousel-caption">
                    <h2>Titulares</h2>
                </div>
            </div>
            <% end %>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>


    </header>

    <!-- Page Content -->
    <div class="container">

        <!-- Marketing Icons Section -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    ¡Últimas noticias!
                </h1>
            </div>

            <% @news_items.each do |news_item| %>
            
            <div class="col-lg-10 col-lg-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-chevron-circle-up"></i> <%= news_item.title %></h4>
                        <div style="text-align: right;">
                         <%= news_item.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
                     </div>
                 </div>
                 <div class="panel-body">
                    <%= news_item.lead %>
                </div>

                <div class='row'>
                  <div class='col-lg-8 col-lg-offset-2'>
                    <hr>
                </div>
            </div>

              <%= form_for(news_item) do |f| %>
              <div class="control-group form-group">
                <div class="controls">
                  <%= f.text_area :body, class: 'form-control',
                  cols: '100', :readonly=>true%>
                </div>
              </div>
              <% end %>

            <div class="panel-footer">
             <div>
                 <%= link_to "#{news_item.comments.count} ", news_item_comments_path(news_item.id, _index: true, _admin: false) %> 
                 <i class="fa fa-comments-o "></i>
                 
             </div>

             <div style="text-align: right;"> <i class="fa fa-plus-square-o" aria-hidden="true"></i>

                 <%= link_to  'Ver más', new_news_item_comment_path(news_item.id, _index: true, _admin: false) %>
             </div>


         </div>
     </div>
 </div>

 <% end %>


</div>
<!-- /.row -->

<!-- Footer -->
<%= render "layouts/footer" %>


</div>
<!-- /.container -->

<!-- jQuery -->
<script src="js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>

<!-- Script to Activate the Carousel -->
<script>
    $('.carousel').carousel({
        interval: 3000 //changes the speed
    })


    $(function() {
        $('textarea').each(function() {
            $(this).height($(this).prop('scrollHeight'));
        });
    });

</script>

</body>

</html>